ktor:
  deployment:
    port: ${PORT:8080}
  application:
    modules:
      - com.vehicletrackingapp.backend.ApplicationKt.module

jwt:
  secret: ${JWT_SECRET:your_super_secret_key_here}
  issuer: ${JWT_ISSUER:http://0.0.0.0:8080}
  audience: ${JWT_AUDIENCE:http://0.0.0.0:8080}
  realm: "Access to 'Vehicle Tracking App'"

database:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/neondb}
  user: ${DATABASE_USER:postgres}
  password: ${DATABASE_PASSWORD:password}
